services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./models_saved:/app/models_saved
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app

  dashboard:
    build: .
    command: streamlit run src/dashboard/app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - ./models_saved:/app/models_saved
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
    depends_on:
      - api
